FROM galileo/php:5.6

MAINTAINER Kamil Ronewicz <galileox86@gmail.com>

ENV COMPOSER_BIN_DIR="/usr/local/bin"
ENV COMPOSER_ALLOW_SUPERUSER="true"

RUN composer global require "phpunit/phpunit=5.*" --prefer-dist
